name: 🩺 Continuous integration ⏩

on:
  push:
    branches: [main]
    paths: ['scripts/**','src/**','test/**']
  pull_request:
    types: [opened, reopened]
    branches: [main]
    paths: ['scripts/**','src/**','test/**']
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  call-workflow:
    uses: brianary/actions/.github/workflows/continuous-integration.yml@main
