name: 📦 Publish module to PowerShell Gallery ⏩

on:
  push:
    tags:
      - v[0-9]*

permissions:
  contents: write
  security-events: write
  actions: read

jobs:
  call-workflow:
    uses: brianary/actions/.github/workflows/powershell-gallery-publish.yml@main
    with:
        version: ${{ github.ref }}
    secrets:
        gallerykey: ${{ secrets.GALLERYKEY }}
        gh_token: ${{ secrets.GITHUB_TOKEN }}

