name: Publish module to PowerShell Gallery
on:
  workflow_run:
    workflows: [".NET build and test"]
    types: [completed]
    branches: [main]
jobs:
  publish:
    name: Publish to PowerShell Gallery
    runs-on: windows-latest
    steps:
      - name: Publish module
        uses: brianary/powershell-gallery-publish@v1
        with:
          gallery-key: ${{ secrets.gallerykey }}
